FROM python:3.12

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY . .

RUN uv sync --frozen

CMD ["uv", "run", "uvicorn", "src.query:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]